image: maven:3-jdk-8

stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MAVEN_CLI_OPTS: " --batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -DAWS_S3_ID=$AWS_ACCESS_KEY_ID -DAWS_S3_PASSWORD=$AWS_SECRET_KEY"
  DEV_SERV_IP: "$DEV_SERV_IP"
  DEV_SERV_USERNAME: "$DEV_SERV_USERNAME"
  DEV_SERV_SECRET_KEY: "$DEV_SERV_SECRET_KEY"

before_script:
  - mkdir -p ~/.ssh
  - ssh-keyscan -H  $DEV_SERV_IP >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  #- apt install psmisc


cache:
  paths:
    - .m2/repository/

deploy_dev:
  stage: deploy
  script:
    - cat $DEV_SERV_SECRET_KEY > key.pem
    - chmod 400 key.pem
    - mvn -f pom.xml clean package -DskipTests -Denv=dev $MAVEN_CLI_OPTS
    - scp -i key.pem app/target/app-0.0.1-SNAPSHOT.jar $DEV_SERV_USERNAME@$DEV_SERV_IP:app-dev/app-dev.jar
    - /bin/sh -c "ssh -i key.pem $DEV_SERV_USERNAME@$DEV_SERV_IP 'bash -s' < scripts/deploy_dev.sh"

  only:
    - new_dev


